name: create release on tag

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - run: env GOOS=linux GOARCH=amd64 go build -ldflags "-X main.compiledVersion=${{ GITHUB.REF_NAME }}" -o syncthing-map-linux-amd64 .
      - run: env GOOS=windows GOARCH=amd64 go build -ldflags "-X main.compiledVersion=${{ GITHUB.REF_NAME }}" -o syncthing-map-windows-amd64.exe .

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            syncthing-map-linux-amd64
            syncthing-map-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
